.PHONY: all

all: chal-1 chal-2 chal-3

chal-1:
	@echo "Challenge 1 - 1 : Go"
	@go run ./1/go/main.go ./1/input.txt 1
	@echo "Challenge 1 - 2 : Go"
	@go run ./1/go/main.go ./1/input.txt 2
	@echo ""

chal-2:
	@echo "Challenge 2 - 1 : Go"
	@go run ./2/go/main.go ./2/input.txt 1
	@echo "Challenge 2 - 2 : Go"
	@go run ./2/go/main.go ./2/input.txt 2
	@echo ""

chal-3:
	@echo "Challenge 3 - 1 : Zig"
	@zig run ./3/zig/main.zig -- ./3/input.txt 1
	@echo "Challenge 3 - 2 : Zig"
	@zig run ./3/zig/main.zig -- ./3/input.txt 2
